#######################
# Configuration File  #
#######################
app:
    # backend mode (file-based, broker)
    backend_mode: "file-based"

token:
    # enable token authentication
    enabled: false

    # url identity provider
    url: "http://digital-twin-infrastructure/identity-provider/protocol/openid-connect/token"
    # token maximum age in minutes
    token_max_age: 30

    # username to request token
    username: "user"
    # password for user to request token
    password: "changeme"
    # id of the identity provider client to login
    client_id: "client_id"
    # client secret of the identity provider client to login
    client_secret: "3edkjfjgiw.xngpw"

broker:
    # url to platform broker
    url: "http://digital-twin-infrastructure/orion-ld"

    # tenant name for multi-agent-model
    fiware_service: "rest_mas"
    
    # tenant path for multi-agent-model
    fiware_service_path: "/agent"

    # url to context file
    context_url: "http://digital-twin-infrastructure/ld-context/datamodels.context-ngsild.jsonld"
